<?php


namespace booking\entities\realtor\land;


use booking\entities\behaviors\MetaBehavior;
use booking\entities\Meta;
use booking\entities\realtor\land\Point;
use booking\helpers\SlugHelper;
use lhs\Yii2SaveRelationsBehavior\SaveRelationsBehavior;
use paulzi\nestedsets\NestedSetsBehavior;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;
use yiidreamteam\upload\ImageUploadBehavior;

/**
 * Class Land
 * @package booking\entities\land
 * @property integer $id
 * @property string $name
 * @property integer $cost
 * @property string $points_json
 * @property string $slug
 * @property string $title
 * @property string $description
 * @property string $content
 * @property string $photo
 * @property string $meta_json [json]
 * @mixin ImageUploadBehavior
 */

class Land extends ActiveRecord
{
    /** @var $points Point[]  */
    public $points = [];
    /** @var $meta Meta */
    public $meta;

    public static function create($name, $slug, $cost): self
    {
        $land = new static();
        $land->name = $name;
        $land->slug = empty($slug) ? SlugHelper::slug($name) : $slug;
        $land->cost = $cost;
        return $land;
    }


    public function edit($name, $slug, $cost): void
    {
        $this->name = $name;
        $this->slug = empty($slug) ? SlugHelper::slug($name) : $slug;
        $this->cost = $cost;
    }

    public function setPage($title, $description, $content)
    {
        $this->title = $title;
        $this->description = $description;
        $this->content = $content;
    }

    public function setMeta(Meta $meta)
    {
        $this->meta = $meta;
    }

    public function setPhoto(UploadedFile $photo)
    {
        $this->photo = $photo;
    }

    public function setPoints(array $points): void
    {
        $this->points = $points;
    }

    public static function tableName()
    {
        return '{{%land_anonymous}}';
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub

        $points = json_decode($this->getAttribute('points_json'));
        foreach ($points as $point) {
            $this->points[] = Point::create($point->latitude, $point->longitude);
        }
    }

    public function beforeSave($insert)
    {
        $this->setAttribute('points_json', json_encode($this->points));
        return parent::beforeSave($insert);
    }

    public function addPoint(Point $point): void
    {
        $this->points[] = $point;
    }

    public function clearPoints(): void
    {
        $this->points = [];
    }
    public function behaviors()
    {
        return [
            MetaBehavior::class,
//            NestedSetsBehavior::class,
            [
                'class' => ImageUploadBehavior::class,
                'attribute' => 'photo',
                'createThumbsOnRequest' => true,
                'filePath' => '@staticRoot/origin/realtor/land/[[id]].[[extension]]',
                'fileUrl' => '@static/origin/realtor/land/[[id]].[[extension]]',
                'thumbPath' => '@staticRoot/cache/realtor/land/[[profile]]_[[id]].[[extension]]',
                'thumbUrl' => '@static/cache/realtor/land/[[profile]]_[[id]].[[extension]]',
                'thumbs' => [
                    'admin' => ['width' => 100, 'height' => 100],
                    'cart_list' => ['width' => 140, 'height' => 250],
                    'cart_list_2' => ['width' => 140, 'height' => 140],
                    'button_image' => ['width' => 400, 'height' => 600],
                    'button_image_mobile' => ['width' => 300, 'height' => 300],
                ],
            ],
        ];
    }
}